<?php if (! \Widgetizer\Service\ShareRegistery::isManagementAllowed())
    return ; // It's not necessary to render UI Management
?>

<?php $this->inlineScript()->captureStart(); ?>
// <script type="text/javascript">
    (function($){
        $( window ).load(function() {
            $('#builderfront_loader').fadeOut();
        });
    })(jQuery);
// </script>
<?php $this->inlineScript()->captureEnd();

$this->inlineScript()
    ->appendFile($this->basePath().'/builderfront/js/jquery-ui.min.js')
    ->appendFile($this->basePath().'/builderfront/js/jquery.ui.touch-punch.min.js')
    ->appendFile($this->basePath().'/builderfront/js/main.js')
;
// set widgets rest api service
$restUrl = $this->url(
    \yimaAdminor\Module::ADMIN_DEFAULT_ROUTE_NAME,
    array(
        'module'     => 'Widgetizer',
        'controller' => 'WidgetManagementRest',
        'action'     => '', // disable default action, using rest call instead
    )
);
$this->inlineScript()
    ->captureStart();
?>
// <script>
    (function($){
        $.fn.widgetizerDrop.restUrl = '<?php echo $restUrl ?>';
    })(jQuery);
// </script>
<?php
$this->inlineScript()
    ->captureEnd();

$this->headLink()
    ->appendStylesheet($this->basePath().'/builderfront/css/style.css')
    ->appendStylesheet($this->basePath().'/builderfront/css/skin.css')
    ->appendStylesheet($this->basePath().'/builderfront/fonts/font-awesome/css/font-awesome.min.css')
;

// Enable Widgetator scripts to ajax calls
$this->widgetAjaxy()
    ->attachScripts();

$theme = $this->theme()->getParentTheme();
while($theme && !$theme->isFinalTheme()) {
    $theme = $theme->getParentTheme();
}

d_r($theme->getName());
d_r($theme->getTemplate());

?>

<div id="builderfront_loader">
    <img src="<?php echo $this->basePath(); ?>/builderfront/images/loading.gif" alt="Loading...">
    <?php echo $this->translate('Loading elements...', 'Widgetizer');?>
</div>

<div id="widgetizer-inplacehtmleditor" class="builderfront_element_dragable">
    <img src="<?php echo $this->basePath(); ?>/builderfront/images/widget.jpg">
</div>
